services:
  picpay_django:
    container_name: picpay-server
    build:
      context: .
    image: django-picpay:dev
    command: >
      sh -c "
        while ! nc -z $$POSTGRES_HOST $$POSTGRES_PORT; do
          echo 'Waiting for Postgres...' && sleep 2;
        done &&
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - picpay_db

  picpay_db:
    container_name: picpay-db
    image: postgres:17-alpine
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

volumes:
  database:
